// Based on https://stackoverflow.com/questions/1550249/programmatically-change-the-assemblyversion-and-assemblyfileversion-attributes
// and https://stackoverflow.com/questions/17123991/t4-reference-a-const-in-a-static-class-at-compile-time

// This is an autogenerated AssemblyInfo.cs file, it will be updated per build

using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

using MelonLoader;
using TideFusionUpdater;

[assembly: AssemblyTitle(TideUpdaterPlugin.Name)]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany(null)]
[assembly: AssemblyProduct(TideUpdaterPlugin.Name)]
[assembly: AssemblyCopyright("Created by " + TideUpdaterPlugin.Author)]
[assembly: AssemblyTrademark(null)]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
//[assembly: Guid("")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: MelonInfo(typeof(TideUpdaterPlugin), TideUpdaterPlugin.Name, "1.0.0", TideUpdaterPlugin.Author, null)]

[assembly: MelonGame("Stress Level Zero", "BONELAB")]